### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Doomsdayrs**
To add some basic details of the project.

### CODE REVIEW

**Comment by luk1337** [comment]
Contributions are done through gerrit — https://wiki.lineageos.org/how-to/submitting-patches/ / https://review.lineageos.org/Documentation/user-upload.html
Also upstream is at @LineageOS, not @lineage-next.

**Comment by Doomsdayrs** [comment]
> Contributions are done through gerrit — https://wiki.lineageos.org/how-to/submitting-patches/ / https://review.lineageos.org/Documentation/user-upload.html Also upstream is at @LineageOS, not @lineage-next.

Oops! Did not know. Inquiry: How would I have known?

**Comment by luk1337** [comment]
> > Contributions are done through gerrit — https://wiki.lineageos.org/how-to/submitting-patches/ / https://review.lineageos.org/Documentation/user-upload.html Also upstream is at @LineageOS, not @lineage-next.
> 
> Oops! Did not know. Inquiry: How would I have known?

wiki? github org description?

**Comment by Doomsdayrs** [comment]
> > > Contributions are done through gerrit — https://wiki.lineageos.org/how-to/submitting-patches/ / https://review.lineageos.org/Documentation/user-upload.html Also upstream is at @LineageOS, not @lineage-next.
> > 
> > 
> > Oops! Did not know. Inquiry: How would I have known?
> 
> wiki? github org description?

The github description for `lineage-next` has no notation.

I mainly woke up to a desire to contribute, so I looked for "lineage os gallery" and found what I believed to be the source (here).

Will contribute a README properly that redirects people to the wiki.

**Comment by luk1337** [comment]
I don't think that kind of readme is really useful. I'd personally prefer if you did something more creative than readme.

**Comment by Doomsdayrs** [comment]
> I don't think that kind of readme is really useful. I'd personally prefer if you did something more creative than readme.

The README would have been useful for us this morning, as it would have enabled me to go through the proper process without spending your time.

**Comment by luk1337** [comment]
well, if by chance upstream had that kind of readme, you probably wouldn't see it anyway since this repo is basically 6 months behind upstream...

**Pull request closed without merging**
